'use server';
import { revalidatePath } from 'next/cache';
import { createClient } from '@/lib/supabase/server';
import { obtenerUsuario } from '@/lib/sesion';
export interface ResultadoAccion { ok: boolean; mensaje: string; contratoId?: string; }
async function permitido() { const usuario = await obtenerUsuario(); return usuario && ['administrador', 'service_logistician'].includes(usuario.rol); }
function periodo(mesInicio: string, desplazamiento: number) { const [anio, mes] = mesInicio.split('-').map(Number); const total = anio * 12 + mes - 1 + desplazamiento; return `${Math.floor(total / 12)}-${String((total % 12) + 1).padStart(2, '0')}-01`; }
export async function crearContrato(_previo: ResultadoAccion | null, formData: FormData): Promise<ResultadoAccion> { if (!await permitido()) return { ok: false, mensaje: 'No tienes permiso para administrar contratos.' }; const numero = String(formData.get('numero') || '').trim(); const clienteNombre = String(formData.get('clienteNombre') || '').trim(); const coordinadorId = String(formData.get('coordinadorId') || '').trim(); const mesInicio = String(formData.get('mesInicio') || '').trim(); const cantidad = Number(formData.get('cantidadVisitas') || 0); const cada = Number(formData.get('cadaCuantosMeses') || 0); if (!numero || !clienteNombre || !coordinadorId || !/^\d{4}-\d{2}$/.test(mesInicio) || !Number.isInteger(cantidad) || cantidad < 1 || cantidad > 60 || !Number.isInteger(cada) || cada < 1 || cada > 12) return { ok: false, mensaje: 'Completa correctamente los datos obligatorios.' }; const supabase = await createClient(); const { data: cliente, error: clienteError } = await supabase.from('clientes').insert({ nombre: clienteNombre, codigo_cliente: String(formData.get('codigoCliente') || '').trim() || null, ciudad: String(formData.get('ciudad') || '').trim() || null, direccion: String(formData.get('direccion') || '').trim() || null, nombre_contacto: String(formData.get('nombreContacto') || '').trim() || null, telefono_contacto: String(formData.get('telefonoContacto') || '').trim() || null, correo_cliente: String(formData.get('correoCliente') || '').trim() || null }).select('id').single(); if (clienteError || !cliente) return { ok: false, mensaje: clienteError?.message ?? 'No se pudo crear el cliente.' }; const { data: contrato, error: contratoError } = await supabase.from('contratos').insert({ numero, cliente_id: cliente.id, coordinador_id: coordinadorId, asesor: String(formData.get('asesor') || '').trim() || null, valido_desde: String(formData.get('validoDesde') || '').trim() || null, valido_hasta: String(formData.get('validoHasta') || '').trim() || null, plantilla_materiales: String(formData.get('plantillaMateriales') || '').trim() || null, activo: true }).select('id').single(); if (contratoError || !contrato) return { ok: false, mensaje: contratoError?.message ?? 'No se pudo crear el contrato.' }; const visitas = Array.from({ length: cantidad }, (_, i) => ({ contrato_id: contrato.id, periodo: periodo(mesInicio, i * cada), numero_visita: String(i + 1), estado: 'pendiente' as const })); const { error: visitasError } = await supabase.from('visitas').insert(visitas); if (visitasError) return { ok: false, mensaje: `Contrato creado, pero falló el cronograma: ${visitasError.message}`, contratoId: contrato.id }; revalidatePath('/materiales/contratos'); revalidatePath('/materiales'); revalidatePath('/clientes'); return { ok: true, mensaje: `Contrato ${numero} creado con ${cantidad} visitas.`, contratoId: contrato.id }; }
export async function cambiarEstadoContrato(contratoId: string, activo: boolean): Promise<ResultadoAccion> { if (!await permitido()) return { ok: false, mensaje: 'No tienes permiso.' }; const { data, error } = await (await createClient()).from('contratos').update({ activo }).eq('id', contratoId).select('id'); if (error) return { ok: false, mensaje: error.message }; if (!data?.length) return { ok: false, mensaje: 'No se pudo actualizar el contrato.' }; revalidatePath('/materiales/contratos'); return { ok: true, mensaje: activo ? 'Contrato reactivado.' : 'Contrato desactivado.' }; }
export async function guardarPlantillaMateriales(contratoId: string, plantilla: string): Promise<ResultadoAccion> { if (!await permitido()) return { ok: false, mensaje: 'No tienes permiso.' }; const { data, error } = await (await createClient()).from('contratos').update({ plantilla_materiales: plantilla.trim() || null }).eq('id', contratoId).select('id'); if (error) return { ok: false, mensaje: error.message }; if (!data?.length) return { ok: false, mensaje: 'No se pudo actualizar la plantilla.' }; revalidatePath('/materiales/contratos'); return { ok: true, mensaje: 'Plantilla guardada.' }; }
