'use client';

import { useActionState, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { cambiarEstadoUsuario, guardarUsuario, restablecerContrasenaUsuario, type ResultadoAccion } from '@/app/admin/acciones';
import type { UsuarioAdmin } from '@/app/admin/usuarios/page';

const ETIQUETA_ROL = { administrador: 'Administrador', coordinador: 'Coordinador', service_logistician: 'Service Logistician' } as const;

export default function FilaUsuario({ usuario, esYo }: { usuario: UsuarioAdmin; esYo: boolean }) {
  const router = useRouter(); const [editando, setEditando] = useState(false); const [aviso, setAviso] = useState<ResultadoAccion | null>(null); const [pendiente, iniciar] = useTransition();
  const [resultado, enviar, guardando] = useActionState<ResultadoAccion | null, FormData>(async (previo, formData) => { const r = await guardarUsuario(previo, formData); if (r.ok) { setEditando(false); router.refresh(); } return r; }, null);
  function alternarAcceso() { iniciar(async () => { const r = await cambiarEstadoUsuario(usuario.id, !usuario.activo); setAviso(r); if (r.ok) router.refresh(); }); }
  function restablecerClave() { iniciar(async () => { const r = await restablecerContrasenaUsuario(usuario.id); setAviso(r); if (r.ok) router.refresh(); }); }
  const campo = 'w-full rounded-lg border border-[#E4E7EB] px-2 py-1.5 text-sm outline-none focus:border-[#FDC100] focus:ring-2 focus:ring-[#FDC100]/25';
  if (editando) return <tr className="border-t border-[#F1F2F4] bg-[#FFF7DB]/40"><td colSpan={4} className="px-5 py-4"><form action={enviar} className="space-y-3"><input type="hidden" name="id" value={usuario.id} /><div className="grid grid-cols-1 gap-2 md:grid-cols-4"><input name="nombre" defaultValue={usuario.nombre} placeholder="Nombre" className={campo} required /><input name="correo" type="email" defaultValue={usuario.correo} placeholder="nombre@kaeser.com" className={campo} required /><select name="rol" defaultValue={usuario.rol} className={campo}>{Object.entries(ETIQUETA_ROL).map(([valor, texto]) => <option key={valor} value={valor}>{texto}</option>)}</select><input name="sucursal" defaultValue={usuario.sucursal} placeholder="Sucursal" className={campo} required /></div>{resultado && <p className={`rounded-lg px-3 py-2 text-sm ${resultado.ok ? 'bg-[#E8F1EC] text-[#14432A]' : 'bg-[#FEECEC] text-[#B42318]'}`}>{resultado.mensaje}</p>}<div className="flex gap-2"><button type="submit" disabled={guardando} className="rounded-lg bg-[#0C0C0C] px-4 py-2 text-sm font-bold text-[#FDC100] disabled:opacity-60">{guardando ? 'Guardando…' : 'Guardar'}</button><button type="button" onClick={() => setEditando(false)} className="rounded-lg border border-[#E4E7EB] px-4 py-2 text-sm font-bold">Cancelar</button></div></form></td></tr>;
  return <tr className={`border-t border-[#F1F2F4] ${!usuario.activo ? 'opacity-55' : ''}`}><td className="px-5 py-3"><p className="text-sm font-bold">{usuario.nombre}{esYo && <span className="ml-2 text-[0.65rem] text-[#6B7280]">(tú)</span>}</p><p className="font-mono text-xs text-[#6B7280]">{usuario.correo}</p>{aviso && <p className={`mt-1 text-xs ${aviso.ok ? 'text-[#14432A]' : 'text-[#B42318]'}`}>{aviso.mensaje}</p>}</td><td className="px-5 py-3 text-sm text-[#4B5563]">{ETIQUETA_ROL[usuario.rol]}</td><td className="px-5 py-3 text-sm text-[#4B5563]">{usuario.sucursal}</td><td className="px-5 py-3 text-right"><div className="flex justify-end gap-2"><button onClick={() => setEditando(true)} className="rounded-lg border border-[#E4E7EB] px-3 py-1.5 text-xs font-bold">Editar</button><button onClick={restablecerClave} disabled={pendiente || esYo} className="rounded-lg border border-[#E4E7EB] bg-[#FFF7DB] px-3 py-1.5 text-xs font-bold text-[#8A6A00] disabled:opacity-40">Reset clave</button><button onClick={alternarAcceso} disabled={pendiente || esYo} className={`rounded-lg px-3 py-1.5 text-xs font-extrabold disabled:opacity-40 ${usuario.activo ? 'bg-[#FEECEC] text-[#B42318]' : 'bg-[#E8F1EC] text-[#14432A]'}`}>{usuario.activo ? 'Desactivar' : 'Activar'}</button></div></td></tr>;
}
