import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MenuLateral from "@/components/MenuLateral";
import { ProveedorToast } from "@/components/ui/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ProveedorToast>
          <div className="flex min-h-screen flex-1 overflow-hidden">
            <MenuLateral />
            <main className="min-w-0 flex-1 overflow-y-auto">{children}</main>
          </div>
        </ProveedorToast>
      </body>
    </html>
  );
}
