import Link from 'next/link';
import { Suspense } from 'react';
import { createClient } from '@/lib/supabase/server';
import { requerirAcceso } from '@/lib/sesion';
import { rangoMes, hoyIso, MESES, aniosDisponibles } from '@/lib/fechas';
import SelectorPeriodo from '@/components/admin/SelectorPeriodo';
import MetricasLogistica from '@/components/admin/MetricasLogistica';

export const dynamic = 'force-dynamic';
interface FilaAvance { coordinador_id: string; coordinador_nombre: string; sucursal: string; coordinador_activo: boolean; total: number; ejecutadas: number; programadas: number; pendientes: number; reprogramadas: number; }
type Props = { searchParams: Promise<{ anio?: string; mes?: string }> };
const pct = (parte: number, total: number) => total ? Math.round((parte / total) * 100) : 0;
function colorCumplimiento(porcentaje: number) { return porcentaje >= 80 ? '#14432A' : porcentaje >= 50 ? '#FDC100' : '#DC2626'; }

export default async function PanelNacional({ searchParams }: Props) {
  await requerirAcceso('/admin');
  const p = await searchParams; const hoy = hoyIso();
  const anio = Number(p.anio) || Number(hoy.slice(0, 4)); const mes = Number(p.mes) || Number(hoy.slice(5, 7));
  const { primerDia } = rangoMes(anio, mes); const supabase = await createClient();
  const { data, error } = await supabase.from('vista_admin_avance').select('*').eq('periodo', primerDia);
  if (error) return <Marco anio={anio} mes={mes}><div className="rounded-xl border border-[#F6CFCB] bg-[#FEECEC] p-4 text-sm text-[#B42318]">No se pudo cargar el avance: {error.message}</div></Marco>;
  const filas = (data ?? []) as FilaAvance[];
  const general = filas.reduce((acumulado, fila) => ({ total: acumulado.total + fila.total, ejecutadas: acumulado.ejecutadas + fila.ejecutadas, programadas: acumulado.programadas + fila.programadas, pendientes: acumulado.pendientes + fila.pendientes, reprogramadas: acumulado.reprogramadas + fila.reprogramadas }), { total: 0, ejecutadas: 0, programadas: 0, pendientes: 0, reprogramadas: 0 });
  const sucursalesMap = new Map<string, { total: number; ejecutadas: number; coordinadores: number }>();
  for (const fila of filas) { const actual = sucursalesMap.get(fila.sucursal) ?? { total: 0, ejecutadas: 0, coordinadores: 0 }; actual.total += fila.total; actual.ejecutadas += fila.ejecutadas; actual.coordinadores += 1; sucursalesMap.set(fila.sucursal, actual); }
  const sucursales = [...sucursalesMap.entries()].map(([sucursal, valores]) => ({ sucursal, ...valores, cumplimiento: pct(valores.ejecutadas, valores.total) })).sort((a, b) => b.cumplimiento - a.cumplimiento);
  const coordinadores = filas.map((fila) => ({ ...fila, cumplimiento: pct(fila.ejecutadas, fila.total) })).sort((a, b) => b.cumplimiento - a.cumplimiento || a.coordinador_nombre.localeCompare(b.coordinador_nombre, 'es'));

  return <Marco anio={anio} mes={mes}><div className="mb-4 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metrica titulo="Visitas del mes" valor={general.total} /><Metrica titulo="Ejecutadas" valor={general.ejecutadas} color="#14432A" /><Metrica titulo="Cumplimiento" valor={`${pct(general.ejecutadas, general.total)}%`} barra={pct(general.ejecutadas, general.total)} /><Metrica titulo="Sucursales" valor={sucursales.length} /></div>{!filas.length ? <div className="rounded-[22px] border border-[#E4E7EB] bg-white p-10 text-center"><p className="font-semibold text-[#6B7280]">No hay visitas registradas en {MESES[mes - 1]} {anio}.</p></div> : <div className="grid grid-cols-1 gap-4 xl:grid-cols-[380px_1fr]"><section className="rounded-[22px] border border-[#E4E7EB] bg-white shadow-sm"><header className="border-b border-[#E4E7EB] px-5 py-3"><h2 className="text-sm font-extrabold">Por sucursal</h2></header><ul className="divide-y divide-[#F1F2F4]">{sucursales.map((s) => <li key={s.sucursal} className="px-5 py-3"><div className="mb-1.5 flex items-baseline justify-between"><span className="truncate text-sm font-bold">{s.sucursal}</span><span className="text-sm font-extrabold" style={{ color: colorCumplimiento(s.cumplimiento) }}>{s.cumplimiento}%</span></div><Barra porcentaje={s.cumplimiento} /><p className="mt-1 text-[0.7rem] text-[#6B7280]">{s.ejecutadas} de {s.total} visitas · {s.coordinadores} coordinador{s.coordinadores === 1 ? '' : 'es'}</p></li>)}</ul></section><section className="overflow-hidden rounded-[22px] border border-[#E4E7EB] bg-white shadow-sm"><header className="border-b border-[#E4E7EB] px-5 py-3"><h2 className="text-sm font-extrabold">Por coordinador</h2></header><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-[#f8f9fa] text-[0.7rem] font-extrabold uppercase text-[#6B7280]"><tr><th className="px-5 py-2.5">Coordinador</th><th className="px-5 py-2.5">Sucursal</th><th className="px-3 py-2.5 text-center">Ejec.</th><th className="px-3 py-2.5 text-center">Total</th><th className="px-5 py-2.5">Cumplimiento</th></tr></thead><tbody>{coordinadores.map((c) => <tr key={c.coordinador_id} className="border-t border-[#F1F2F4]"><td className="px-5 py-2.5 text-sm font-bold">{c.coordinador_nombre}{!c.coordinador_activo && <span className="ml-2 rounded bg-[#FEECEC] px-1.5 py-0.5 text-[0.6rem] text-[#B42318]">inactivo</span>}</td><td className="px-5 py-2.5 text-sm text-[#4B5563]">{c.sucursal}</td><td className="px-3 py-2.5 text-center font-bold text-[#14432A]">{c.ejecutadas}</td><td className="px-3 py-2.5 text-center text-[#4B5563]">{c.total}</td><td className="px-5 py-2.5"><div className="flex items-center gap-2"><Barra porcentaje={c.cumplimiento} /><span className="w-10 text-right text-sm font-extrabold" style={{ color: colorCumplimiento(c.cumplimiento) }}>{c.cumplimiento}%</span></div></td></tr>)}</tbody></table></div></section></div>}<Suspense fallback={null}><MetricasLogistica periodo={primerDia} /></Suspense></Marco>;
}
function Marco({ anio, mes, children }: { anio: number; mes: number; children: React.ReactNode }) { return <div className="min-h-screen bg-[#f8f9fa]"><div className="mx-auto max-w-[1600px] p-4 md:p-6"><header className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-extrabold">Panel Nacional</h1><p className="text-sm text-[#6B7280]">Avance de {MESES[mes - 1]} {anio}</p></div><div className="flex items-center gap-2"><SelectorPeriodo anio={anio} mes={mes} anios={aniosDisponibles()} /><Link href="/admin/sabana" className="rounded-xl border border-[#E4E7EB] bg-white px-4 py-2 text-sm font-bold">Vista sábana</Link><Link href="/admin/usuarios" className="rounded-xl bg-[#0C0C0C] px-4 py-2 text-sm font-bold text-[#FDC100]">Usuarios</Link></div></header>{children}</div></div>; }
function Metrica({ titulo, valor, color, barra }: { titulo: string; valor: number | string; color?: string; barra?: number }) { return <div className="relative overflow-hidden rounded-[25px] border border-[#E4E7EB] bg-white p-5 shadow-sm"><p className="text-[0.7rem] font-extrabold uppercase text-[#6B7280]">{titulo}</p><p className="mt-1 text-3xl font-extrabold" style={{ color: color ?? '#0C0C0C' }}>{valor}</p>{barra !== undefined && <div className="absolute bottom-0 left-0 h-1.5 w-full bg-[#E9ECEF]"><div className="h-1.5" style={{ width: `${barra}%`, background: colorCumplimiento(barra) }} /></div>}</div>; }
function Barra({ porcentaje }: { porcentaje: number }) { return <div className="h-2 min-w-[70px] flex-1 overflow-hidden rounded-full bg-[#E9ECEF]"><div className="h-full rounded-full" style={{ width: `${porcentaje}%`, background: colorCumplimiento(porcentaje) }} /></div>; }
