import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import FormularioMateriales from './FormularioMateriales';
import { formatearPeriodo, formatearFecha, ETIQUETA_ESTADO } from '@/lib/formato';
import type { EstadoVisita, EstadoMaterial } from '@/types/db';

export default async function PanelMateriales({ visitaId, editable }: { visitaId: string; editable: boolean }) {
  const supabase = await createClient();
  const { data, error } = await supabase.from('vista_calendario').select('visita_id, cliente_nombre, ciudad, direccion, contrato_numero, coordinador_nombre, numero_visita, periodo, estado, fecha_inicio, hora_inicio, os, estado_materiales, detalle_materiales, tecnicos_nombres').eq('visita_id', visitaId).maybeSingle();
  return <><Link href="?" scroll={false} aria-label="Cerrar" className="fixed inset-0 z-40 bg-[#0C0C0C]/50 backdrop-blur-[2px]" /><aside className="fixed right-0 top-0 z-50 h-full w-full max-w-md overflow-y-auto border-l border-[#E4E7EB] bg-white p-5 shadow-2xl"><Link href="?" scroll={false} className="absolute right-4 top-4 flex h-9 w-9 items-center justify-center rounded-full bg-[#E9ECEF]">✕</Link>{error || !data ? <p className="mt-10 rounded-xl border border-[#F6CFCB] bg-[#FEECEC] p-4 text-sm text-[#B42318]">No se pudo cargar la visita{error ? `: ${error.message}` : '.'}</p> : <><header className="mb-4 border-b border-[#E4E7EB] pb-4"><span className="mb-2 inline-block rounded-md bg-[#0C0C0C] px-2.5 py-1 text-[0.65rem] font-extrabold uppercase text-[#FDC100]">Alistamiento · {formatearPeriodo(data.periodo)}</span><h2 className="text-lg font-extrabold text-[#0C0C0C]">{data.cliente_nombre}</h2><p className="mt-1 font-mono text-xs text-[#6B7280]">Contrato {data.contrato_numero} · Visita {data.numero_visita ?? '—'}</p></header><dl className="mb-5 space-y-1.5 rounded-xl border border-[#E4E7EB] bg-[#f8f9fa] p-3 text-sm"><Fila etiqueta="Coordinador" valor={data.coordinador_nombre ?? '—'} /><Fila etiqueta="Fecha" valor={data.fecha_inicio ? formatearFecha(data.fecha_inicio) : 'Sin programar'} /><Fila etiqueta="Técnicos" valor={data.tecnicos_nombres?.length ? data.tecnicos_nombres.join(', ') : 'Sin asignar'} /><Fila etiqueta="Dirección" valor={[data.direccion, data.ciudad].filter(Boolean).join(' · ') || '—'} /><Fila etiqueta="Estado" valor={ETIQUETA_ESTADO[data.estado as EstadoVisita] ?? '—'} /></dl>{editable ? <FormularioMateriales visitaId={data.visita_id} estadoMateriales={data.estado_materiales as EstadoMaterial} detalle={data.detalle_materiales} os={data.os} /> : <p className="rounded-xl border border-[#F3DFA0] bg-[#FFF7DB] px-3 py-2 text-sm text-[#8A6A00]">Tu cargo puede consultar el alistamiento, pero no modificarlo.</p>}</>}</aside></>;
}
function Fila({ etiqueta, valor }: { etiqueta: string; valor: string }) { return <div className="flex gap-2"><dt className="shrink-0 font-semibold text-[#6B7280]">{etiqueta}:</dt><dd className="min-w-0 text-[#4B5563]">{valor}</dd></div>; }
