import Link from 'next/link';
import type { FilaCalendario, EstadoMaterial } from '@/types/db';
import { CLASES_MATERIAL, ETIQUETA_MATERIAL, formatearFecha } from '@/lib/formato';
const ORDEN: EstadoMaterial[] = ['pendiente', 'preparado', 'ajustado', 'faltante'];
export default function TablaMateriales({ visitas, editable }: { visitas: FilaCalendario[]; editable: boolean }) {
  const resumen = ORDEN.map((estado) => ({ estado, total: visitas.filter((v) => v.estado_materiales === estado).length }));
  if (!visitas.length) return <div className="rounded-[22px] border border-[#E4E7EB] bg-white p-10 text-center"><p className="font-semibold text-[#6B7280]">No hay visitas para este filtro.</p></div>;
  return <div className="space-y-4"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{resumen.map(({ estado, total }) => <div key={estado} className="rounded-[22px] border border-[#E4E7EB] bg-white p-4 shadow-sm"><p className="text-[0.7rem] font-extrabold uppercase text-[#6B7280]">{ETIQUETA_MATERIAL[estado]}</p><p className="mt-1 text-2xl font-extrabold text-[#0C0C0C]">{total}</p></div>)}</div><div className="overflow-hidden rounded-[22px] border border-[#E4E7EB] bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-[#f8f9fa]"><tr className="text-[0.7rem] font-extrabold uppercase text-[#6B7280]"><th className="px-5 py-3">Cliente y contrato</th><th className="px-5 py-3">Coordinador</th><th className="px-5 py-3">Visita</th><th className="px-5 py-3">Materiales</th><th className="px-5 py-3">OS</th><th className="px-5 py-3 text-right">Acción</th></tr></thead><tbody>{visitas.map((v) => <tr key={v.visita_id} className="border-t border-[#F1F2F4] align-top"><td className="px-5 py-3"><p className="text-sm font-bold">{v.cliente_nombre}</p><p className="font-mono text-xs text-[#6B7280]">CTR {v.contrato_numero}{v.ciudad ? ` · ${v.ciudad}` : ''}</p></td><td className="px-5 py-3 text-sm text-[#4B5563]">{v.coordinador_nombre ?? '—'}</td><td className="px-5 py-3 text-sm text-[#4B5563]">Visita {v.numero_visita ?? '—'}<p className="text-xs text-[#6B7280]">{v.fecha_inicio ? formatearFecha(v.fecha_inicio) : 'Sin fecha'}</p></td><td className="px-5 py-3"><span className={`inline-block rounded-md px-2 py-1 text-[0.7rem] font-extrabold uppercase ${CLASES_MATERIAL[v.estado_materiales]}`}>{ETIQUETA_MATERIAL[v.estado_materiales]}</span>{v.detalle_materiales && <p className="mt-1 max-w-xs whitespace-pre-wrap text-xs text-[#6B7280]">{v.detalle_materiales}</p>}</td><td className="px-5 py-3 font-mono text-sm">{v.os ?? '—'}</td><td className="px-5 py-3 text-right"><Link href={`?visita=${v.visita_id}`} scroll={false} className="inline-block rounded-xl border border-[#E4E7EB] px-3 py-2 text-xs font-bold">{editable ? 'Actualizar' : 'Ver'}</Link></td></tr>)}</tbody></table></div></div></div>;
}
