import { Suspense } from 'react';
import { createClient } from '@/lib/supabase/server';
import { requerirAcceso, puedeEditarMateriales } from '@/lib/sesion';
import { rangoMes, hoyIso, MESES, aniosDisponibles } from '@/lib/fechas';
import type { FilaCalendario } from '@/types/db';
import FiltrosMateriales from '@/components/materiales/FiltrosMateriales';
import TablaMateriales from '@/components/materiales/TablaMateriales';
import PanelMateriales from '@/components/materiales/PanelMateriales';
import FiltrosRapidos from '@/components/materiales/FiltrosRapidos';
export const dynamic = 'force-dynamic';
type Props = { searchParams: Promise<{ anio?: string; mes?: string; material?: string; coordinador?: string; q?: string; visita?: string }> };
export default async function PaginaMateriales({ searchParams }: Props) {
  const usuario = await requerirAcceso('/materiales'); const p = await searchParams; const hoy = hoyIso(); const base = new Date(Date.UTC(Number(hoy.slice(0, 4)), Number(hoy.slice(5, 7)), 1)); const anio = Number(p.anio) || base.getUTCFullYear(); const mes = Number(p.mes) || base.getUTCMonth() + 1; const supabase = await createClient(); const { data: coordinadores } = await supabase.from('usuarios').select('id, nombre').eq('rol', 'coordinador').order('nombre'); const editable = puedeEditarMateriales(usuario.rol);
  return <div className="min-h-screen bg-[#f8f9fa]"><div className="mx-auto max-w-[1600px] p-4 md:p-6"><header className="mb-4"><h1 className="text-2xl font-extrabold">Centro de Materiales</h1><p className="text-sm text-[#6B7280]">Alistamiento de {MESES[mes - 1]} {anio}{!editable && ' · solo lectura'}</p></header><FiltrosMateriales anio={anio} mes={mes} material={p.material ?? ''} coordinador={p.coordinador ?? ''} q={p.q ?? ''} coordinadores={coordinadores ?? []} anios={aniosDisponibles()} /><div className="mt-4"><Suspense fallback={<div className="h-64 animate-pulse rounded-[22px] bg-[#ECEEF1]" />}><Contenido anio={anio} mes={mes} material={p.material ?? ''} coordinador={p.coordinador ?? ''} q={p.q ?? ''} editable={editable} /></Suspense></div></div>{p.visita && <Suspense fallback={null}><PanelMateriales visitaId={p.visita} editable={editable} /></Suspense>}</div>;
}
async function Contenido({ anio, mes, material, coordinador, q, editable }: { anio: number; mes: number; material: string; coordinador: string; q: string; editable: boolean }) { const supabase = await createClient(); const { primerDia } = rangoMes(anio, mes); let consulta = supabase.from('vista_calendario').select('visita_id, contrato_numero, cliente_nombre, ciudad, numero_visita, periodo, estado, fecha_inicio, os, estado_materiales, detalle_materiales, coordinador_nombre, coordinador_id, tecnicos_nombres').eq('periodo', primerDia).order('cliente_nombre').limit(400); if (coordinador) consulta = consulta.eq('coordinador_id', coordinador); if (q) { const seguro = q.replace(/[%,()]/g, ' ').trim(); consulta = consulta.or(`cliente_nombre.ilike.%${seguro}%,contrato_numero.ilike.%${seguro}%`); } const { data, error } = await consulta; if (error) return <div className="rounded-xl border border-[#F6CFCB] bg-[#FEECEC] p-4 text-sm text-[#B42318]">No se pudo cargar el alistamiento: {error.message}</div>; const todas = (data ?? []) as FilaCalendario[]; const conteos = todas.reduce((acumulado, visita) => { acumulado[visita.estado_materiales] = (acumulado[visita.estado_materiales] ?? 0) + 1; return acumulado; }, {} as Record<string, number>); const visitas = material ? todas.filter((visita) => visita.estado_materiales === material) : todas; return <><FiltrosRapidos activo={material} conteos={conteos} /><div className="mt-3"><TablaMateriales visitas={visitas} editable={editable} /></div></>; }
