'use client';

import { createContext, useCallback, useContext, useMemo, useState } from 'react';
type Tipo = 'exito' | 'error' | 'aviso';
interface Aviso { id: number; tipo: Tipo; texto: string; accion?: { etiqueta: string; alPulsar: () => void } }
interface ContextoToast { exito: (texto: string) => void; error: (texto: string) => void; aviso: (texto: string, accion?: Aviso['accion']) => void; mostrar: (r: { ok: boolean; mensaje: string }, accion?: Aviso['accion']) => void }
const Contexto = createContext<ContextoToast | null>(null);
export function useToast() { const ctx = useContext(Contexto); if (!ctx) throw new Error('useToast debe usarse dentro de <ProveedorToast>'); return ctx; }
const ESTILO: Record<Tipo, string> = { exito: 'border-[#C9E0D3] bg-[#E8F1EC] text-[#14432A]', error: 'border-[#F6CFCB] bg-[#FEECEC] text-[#B42318]', aviso: 'border-[#F3DFA0] bg-[#FFF7DB] text-[#8A6A00]' };
export function ProveedorToast({ children }: { children: React.ReactNode }) { const [avisos, setAvisos] = useState<Aviso[]>([]); const quitar = useCallback((id: number) => setAvisos((prev) => prev.filter((a) => a.id !== id)), []); const agregar = useCallback((tipo: Tipo, texto: string, accion?: Aviso['accion']) => { const id = Date.now() + Math.random(); setAvisos((prev) => [...prev, { id, tipo, texto, accion }]); if (tipo === 'exito' && !accion) setTimeout(() => quitar(id), 4000); }, [quitar]); const valor = useMemo(() => ({ exito: (t: string) => agregar('exito', t), error: (t: string) => agregar('error', t), aviso: (t: string, a?: Aviso['accion']) => agregar('aviso', t, a), mostrar: (r: { ok: boolean; mensaje: string }, a?: Aviso['accion']) => agregar(r.ok ? 'exito' : 'error', r.mensaje, a) }), [agregar]); return <Contexto.Provider value={valor}>{children}<div className="pointer-events-none fixed bottom-4 right-4 z-[100] flex w-full max-w-sm flex-col gap-2" role="status" aria-live="polite">{avisos.map((a) => <div key={a.id} className={`pointer-events-auto flex items-start gap-3 rounded-xl border p-3 shadow-lg ${ESTILO[a.tipo]}`}><p className="min-w-0 flex-1 text-sm font-semibold">{a.texto}</p>{a.accion && <button onClick={() => { a.accion?.alPulsar(); quitar(a.id); }} className="text-xs font-bold underline">{a.accion.etiqueta}</button>}<button onClick={() => quitar(a.id)} aria-label="Cerrar">✕</button></div>)}</div></Contexto.Provider>; }
